### ISSUE TITLE
Images are not built

### ISSUE THREAD

**Issue by Ladefuss** [vadimmarkov/webpack-es6-sass-boilerplate#1]
Thank you for this repo. Works perfectly except with images. The "images/logo.png" in the demo html file is not working and i cannot seem to make images work when i change the layout to my own.

**Comment by patrick-hollstein** [comment]
Hi @Ladefuss,

my solution:

1) Open the file ```webpack/webpack.common.js```
2) In line 67 change ```'../images'``` to ```'./images'```

After this change the pictures were linked correctly.

You should also change the same in line 56 for the fonts.

Greeting
Patrick
